//@version=5

// start bb
indicator(shorttitle="BBMA by Boolean", title="BBMA by Boolean", overlay=true, timeframe="", timeframe_gaps=true)

mid_len = input.int(20, minval=1, title="Middle SMA", group="Bollinger Bands")
mid_src = input(close, title="Source", group="Bollinger Bands")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev", group="Bollinger Bands")
bb_offset = input.int(0, "Offset", minval = -500, maxval = 500, group="Bollinger Bands")

basis = ta.sma(mid_src, mid_len)
dev = mult * ta.stdev(mid_src, mid_len)
upper_bb = basis + dev
lower_bb = basis - dev

plot(basis, "Middle", color=#2962FF, offset = bb_offset)
p1 = plot(upper_bb, "Upper", color=#2962FF, offset = bb_offset)
p2 = plot(lower_bb, "Lower", color=#2962FF, offset = bb_offset)
// fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))
// end bb

// start moving average
wma1_len = input.int(5, minval=1, title="WMA 1", group="MA Length")
wma2_len = input.int(5, minval=1, title="WMA 2", group="MA Length")
wma3_len = input.int(10, minval=1, title="WMA 3", group="MA Length")
wma4_len = input.int(10, minval=1, title="WMA 4", group="MA Length")
ema_len = input.int(50, minval=1, title="EMA", group="MA Length")

wma1_src = input(low, title="WMA 1", group="MA Source")
wma2_src = input(high, title="WMA 2", group="MA Source")
wma3_src = input(low, title="WMA 3", group="MA Source")
wma4_src = input(high, title="WMA 4", group="MA Source")
ema_src = input(close, title="EMA", group="MA Source")

wma1_out = ta.wma(wma1_src, wma1_len)
wma2_out = ta.wma(wma2_src, wma2_len)
wma3_out = ta.wma(wma3_src, wma3_len)
wma4_out = ta.wma(wma4_src, wma4_len)
ema_out = ta.ema(ema_src, ema_len)

plot(wma1_out, title="WMA 1", color=#FF00FF)
plot(wma2_out, title="WMA 2", color=color.red)
plot(wma3_out, title="WMA 3", color=color.white)
plot(wma4_out, title="WMA 4", color=color.yellow)
plot(ema_out, title="EMA", color=color.aqua)
// end moving average